apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wapp-dep
  name: wapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wapp-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wapp-dep
    spec:
      containers:
      - image: mohcontreg.azurecr.io/mohzeelaweatherapp
        name: mohzeelaweatherapp
        resources: {}
status: {}
